name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest
    
    env:
      SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install SOPS
      uses: mdgreenwald/mozilla-sops-action@v1.2.0
      
    - name: Rust cache
      uses: Swatinem/rust-cache@v1.3.0
      
    - name: Run tests
      run: cargo test --verbose
